### ISSUE TITLE
Transfer learning

### ISSUE THREAD

**Issue by WathikAhmed** [ThisJustin-code/pretrained-gan-flowers-256#1]
Hi,

I have stylegan2 ada pytorch and I would like to try transfer learning from your .pkl files onto my own dataset.

Do you know the particular command line for something like this?

Thanks.

**Comment by ThisJustin-code** [comment]
Hi @WathikAhmed,

You can use the --resume option with train.py to specify a .pkl file to continue training from. In your case, the command would look something like `python train.py --resume=~/flowers-256-trained.pkl --outdir=~/your-output-directory --data=~/your-own-dataset`

 Hope this helps.

**Comment by WathikAhmed** [comment]
Thanks
